In [2]:
import pandas as pd

In [3]:
df =pd.read_csv("globalAirQuality.csv")

In [4]:
df.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [5]:
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [6]:
df.shape

(18000, 15)

In [7]:
df.nunique()

timestamp        360
country           38
city              50
latitude          50
longitude         50
pm25           15839
pm10           16332
no2            15139
so2             8158
o3             15275
co              1376
aqi              178
temperature    13930
humidity       15725
wind_speed      8058
dtype: int64

In [8]:
df[["city", "aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [9]:
print(df[df["city"] =="Delhi"])

                       timestamp country   city  latitude  longitude    pm25  \
6840  2025-11-04 18:25:17.554219      IN  Delhi    28.704     77.102  44.829
6841  2025-11-04 19:25:17.554219      IN  Delhi    28.704     77.102  38.797
6842  2025-11-04 20:25:17.554219      IN  Delhi    28.704     77.102  54.364
6843  2025-11-04 21:25:17.554219      IN  Delhi    28.704     77.102  26.080
6844  2025-11-04 22:25:17.554219      IN  Delhi    28.704     77.102  18.285
...                          ...     ...    ...       ...        ...     ...
7195  2025-11-19 13:25:17.554219      IN  Delhi    28.704     77.102  16.101
7196  2025-11-19 14:25:17.554219      IN  Delhi    28.704     77.102  48.989
7197  2025-11-19 15:25:17.554219      IN  Delhi    28.704     77.102  37.461
7198  2025-11-19 16:25:17.554219      IN  Delhi    28.704     77.102  77.418
7199  2025-11-19 17:25:17.554219      IN  Delhi    28.704     77.102  62.481

         pm10     no2    so2      o3     co  aqi  temperature  humidity  \
6840   28.334   9.180  6.874  49.548  0.911   89       33.540    40.150
6841   54.046  53.594  3.407  40.532  0.454  133       23.468    30.788
6842  131.193  34.506  3.664  48.325  1.211  131       16.154    55.117
6843   61.262   8.017  6.116  47.416  0.908   61       35.881    86.602
6844   54.259  43.646  6.036  47.786  0.409  109       37.776    55.852
...       ...     ...    ...     ...    ...  ...          ...       ...
7195   19.223  57.290  7.124  63.720  0.568  143       11.819    80.977
7196   68.555  25.099  7.108  38.624  0.712   97       21.355    41.076
7197   14.375  25.422  8.830  48.149  0.469   74       37.608    43.422
7198  121.415   0.139  7.561  47.000  0.845  154       27.715    80.107
7199   87.965  13.657  2.311  63.675  0.800  124       12.333    86.384

      wind_speed
6840       7.473
6841       2.936
6842       2.934
6843       6.232
6844       6.343
...          ...
7195       4.030
7196       9.402
7197       1.466
7198       7.530
7199       1.656

[360 rows x 15 columns]

In [12]:
df.loc[0]

timestamp      2025-11-04 18:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               50.295
pm10                              108.938
no2                                27.998
so2                                 6.539
o3                                 52.568
co                                  1.096
aqi                                   108
temperature                        18.504
humidity                           70.168
wind_speed                          3.725
Name: 0, dtype: object

In [13]:
highest = df.loc[df["aqi"].idxmax(),["city","aqi"]]

In [14]:
print(highest)

city    Helsinki
aqi          231
Name: 17529, dtype: object

In [15]:
lowest = df.loc[df["aqi"].idxmin(), ["city","aqi"]]

In [16]:
print(lowest)

city    London
aqi         16
Name: 960, dtype: object

In [17]:
highest_per_city = df.loc[df.groupby("city")["aqi"].idxmax()]
print(highest_per_city[["city", "aqi","temperature"]])

                   city  aqi  temperature
12956          Auckland  225       14.872
10915           Bangkok  194       16.485
9675            Beijing  183        9.252
7289          Bengaluru  175        5.724
1455             Berlin  182       19.775
3786       Buenos Aires  197       16.320
4325              Cairo  190       20.293
4242          Cape Town  190       24.406
8175            Chennai  182       22.067
15782           Chicago  186       23.810
7024              Delhi  195       34.274
6454               Doha  187       29.275
5461              Dubai  189       11.895
17529          Helsinki  231       25.795
14983  Ho Chi Minh City  179        7.177
10221         Hong Kong  192       26.493
16055           Houston  187        5.332
13529          Istanbul  179       16.492
11564           Jakarta  198       36.710
14149           Karachi  186       17.277
7678            Kolkata  183       19.667
11321      Kuala Lumpur  194       14.922
5213              Lagos  190       19.945
745              London  214       19.055
589         Los Angeles  189       32.858
2075             Madrid  183       10.153
14555            Manila  206       11.027
12360         Melbourne  191       18.600
3115        Mexico City  196       30.738
13229            Moscow  197       22.246
6747             Mumbai  194       32.153
4843            Nairobi  172       33.181
112            New York  192       32.786
8941              Osaka  204       15.277
1154              Paris  187       14.926
5777             Riyadh  182       17.134
2446               Rome  190       29.190
15145     San Francisco  187       12.539
9273              Seoul  183       14.246
9950           Shanghai  167       17.665
10463         Singapore  193       21.696
17153         Stockholm  196        6.929
11891            Sydney  193       34.785
3592          São Paulo  182       13.035
13715            Tehran  177        9.236
8608              Tokyo  183       14.650
2547            Toronto  176       20.461
16455         Vancouver  188       26.642
16767            Warsaw  197       13.000
17815            Zurich  203       20.883

In [32]:
result = highest_per_city[["city","aqi","temperature"]]

In [24]:
result.to_excel("highest_aqi.xlsx", index=False)

In [27]:
#to print first row data
df.loc[0] #usein indexing
df.loc[0:2] #use in printing slicing

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650

## filtering

In [31]:
df[df["aqi"] > 100]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
8,2025-11-05 02:25:17.554219,US,New York,40.713,-74.006,60.914,44.775,40.936,6.779,36.751,1.014,121,24.092,48.148,8.686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787
17993,2025-11-19 11:25:17.554219,CH,Zurich,47.377,8.542,76.613,37.495,29.662,5.419,57.042,1.103,153,20.437,79.602,2.663
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660

In [29]:
df[(df["aqi"]>100) & (df["temperature"] > 30) ]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
14,2025-11-05 08:25:17.554219,US,New York,40.713,-74.006,38.815,121.394,25.969,4.112,44.730,1.124,121,34.481,81.790,3.576
17,2025-11-05 11:25:17.554219,US,New York,40.713,-74.006,63.552,57.838,13.754,4.427,42.251,0.997,127,36.193,62.906,7.097
25,2025-11-05 19:25:17.554219,US,New York,40.713,-74.006,56.954,75.045,29.837,9.541,54.198,1.170,113,31.289,43.279,5.264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17947,2025-11-17 13:25:17.554219,CH,Zurich,47.377,8.542,53.938,75.183,16.255,7.263,67.244,0.457,107,32.584,81.544,7.101
17950,2025-11-17 16:25:17.554219,CH,Zurich,47.377,8.542,70.255,60.620,32.081,2.065,47.803,0.852,140,36.885,34.173,1.748
17975,2025-11-18 17:25:17.554219,CH,Zurich,47.377,8.542,33.406,98.160,44.654,0.807,45.160,0.737,111,30.761,76.073,3.570
17976,2025-11-18 18:25:17.554219,CH,Zurich,47.377,8.542,73.493,89.558,9.313,4.768,51.505,0.745,146,30.909,81.573,1.024
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787

## query method

In [30]:
df.query("aqi > 100 & temperature >37.5") [["city", "aqi"]]

              city  aqi
7         New York  115
120       New York  109
182       New York  133
354       New York  113
459    Los Angeles  107
...            ...  ...
17684       Zurich  104
17691       Zurich  142
17842       Zurich  127
17848       Zurich  127
17874       Zurich  146

[151 rows x 2 columns]

In [22]:
import sys
print(sys.executable)

C:\Users\Saket\anaconda3\envs\deeplearning\python.exe

In [23]:
import sys
!{sys.executable} -m pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5